site_name: Hradební programování
site_description: Online učebnice programování
site_author: David Sládeček

theme:
  name: material
  language: cs

nav:
  - Domů: index.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
